### ISSUE TITLE
#1 How can I make sure the real-time communicatino between clients

### ISSUE THREAD

**Issue by rexcere** [rexcere/TickSystem_BackEnd#1]
I need to ensure the resl-time communication through this platform.
You can use socket.io, message broker.
I want to know which is good for this.
Thanks

**Comment by rexcare** [comment]
In this case, Normally use websocket.
WebSocket is a computer communications protocol, providing full-duplex communication channels over a single TCP connection. The WebSocket protocol was standardized by the IETF as RFC 6455 in 2011. The current API specification allowing web applications to use this protocol is known as WebSockets.

thanks
